### ISSUE TITLE
report is very slow

### ISSUE THREAD

**Issue by SourenP** [ripple/crawl-reporter#1]
` node index.js report 1 5000` takes forever

**Comment by SourenP** [comment]
This is causing it to fall behind the crawler.

The slowness is due to the processing functions in https://github.com/ripple/rippled-network-crawler/blob/master/src/lib/utility.js

**Comment by SourenP** [comment]
`getIpps` takes `0.076` seconds
`getRippleds` takes `0.263` seconds
`getLinks` takes `0.419` seconds

**Comment by SourenP** [comment]
We didn't optimize the utility functions but we came up with an async algorithm (5a45f63a57628e9b245706a80a3a875dae4178d3) which made it ~3x faster.

**Comment by SourenP** [comment]
apparently it still falls behind, I believe the solution to this is to report 1 out of X crawls.

**Comment by hthayko** [comment]
a scalable solution that will enable multiple workers processing the data will be more appropriate

**Comment by SourenP** [comment]
solved by 80e3dc0c110e40fde632a8d73de6d68f6d9fe93a
